### PR TITLE
handle projects with nested package.json files

### PR DESCRIPTION
**Pull request by erikdonohoo**
This fix will handle projects with nested package.json files. 

The problem arises if you have a `.jscsrc` in your project root, but inside the project you have another folder with a `package.json`.  The current code will find that, and see there is no jscsConfig property, and then bail to look for a config on the users home directory.

### CODE REVIEW

**Comment by steelbrain** [comment]
On a side question, why not just spawn a jscs process and do all the complex operations in a separate thread, that way we could also avoid having to find config in our package.
/cc @iam4x

**Comment by erikdonohoo** [comment]
finding the config is a unique problem for every package.  its not as simple as just finding a file with a certain name.  Since we support jscs config in multiple places and ways I'm not sure moving it to another package makes sense.  Also, do you feel this is overly complex?

**Comment by steelbrain** [comment]
@erikdonohoo I wasn't asking to move it to another package, I was asking to spawn the `jscs` executable itself and let it do it's searching and stuff. I feel this is overly complex because this whole package could be written in less than 50 lines. and the main benefit would be that it won't lag the editor for the user as it's gonna be in a separate thread. 
I saw a bug report in a js linter provider recently where the person reported that the editor jams for at least 20 seconds when he lints the materialize file.

**Comment by erikdonohoo** [comment]
Ok, I will work on that.  Thanks @steelbrain

**Comment by iam4x** [comment]
This is not related anymore, we have change the way `linter-jscs` use config.

**Pull request closed without merging**
